// backend/src/services/killChain.js
const TACTICS = [
  'Reconnaissance', 'Resource Development', 'Initial Access', 'Execution',
  'Persistence', 'Privilege Escalation', 'Defense Evasion', 'Credential Access',
  'Discovery', 'Lateral Movement', 'Collection', 'Command and Control',
  'Exfiltration', 'Impact',
];

const W = { high: 1, medium: 0.6, low: 0.3 };
const weight = (c) => W[c] != null ? W[c] : 0.3;

function weightedCoverage(findings = []) {
  const byTactic = new Map();
  for (const f of findings) {
    if (!f.mitre_tactic) continue;
    const w = weight(f.confidence);
    if (!byTactic.has(f.mitre_tactic) || byTactic.get(f.mitre_tactic) < w) {
      byTactic.set(f.mitre_tactic, w);
    }
  }
  const score = [...byTactic.values()].reduce((a, b) => a + b, 0) / TACTICS.length;
  return { covered: byTactic.size, total: TACTICS.length, score };
}

function blindSpots(findings = []) {
  const present = new Set(findings.map((f) => f.mitre_tactic).filter(Boolean));
  return TACTICS.filter((t) => !present.has(t));
}

function causalChains(findings = []) {
  const byId = new Map(findings.map((f) => [f.id, f]));
  const pointed = new Set(findings.map((f) => f.links_to).filter(Boolean));
  const roots = findings.filter((f) => !pointed.has(f.id));
  const starts = roots.length ? roots : findings.slice(0, 1);
  const chains = [];
  for (const root of starts) {
    const seen = new Set();
    const chain = [];
    let cur = root;
    while (cur && !seen.has(cur.id)) {
      seen.add(cur.id);
      chain.push(cur.id);
      cur = cur.links_to ? byId.get(cur.links_to) : null;
    }
    if (chain.length) chains.push(chain);
  }
  return chains;
}

const SCORE = { high: 100, medium: 60, low: 30 };

function navigatorLayer(findings = [], caseName = 'Heimdall') {
  const techniques = findings
    .filter((f) => f.mitre_technique)
    .map((f) => ({
      techniqueID: String(f.mitre_technique).split('.')[0],
      score: SCORE[f.confidence] != null ? SCORE[f.confidence] : 30,
      comment: f.mitre_tactic || '',
      color: '',
      enabled: true,
    }));
  return {
    name: `${caseName} — Kill Chain`,
    versions: { attack: '14', navigator: '4.9.1', layer: '4.5' },
    domain: 'enterprise-attack',
    description: 'Generated by Heimdall DFIR',
    techniques,
  };
}

module.exports = { TACTICS, weightedCoverage, blindSpots, causalChains, navigatorLayer };
