import {
  Shield,
  LayoutDashboard,
  Activity,
  Network,
  Crosshair,
  FolderOpen,
  Monitor,
  Globe,
  SlidersHorizontal,
  FileText,
  Settings,
  Search,
  Bell,
  Filter,
  Flag,
  Link,
  Upload,
  Zap,
  User,
  ChevronRight,
  Info,
  ScrollText,
  Circle,
} from 'lucide-react';

export const ICONS = {
  shield:    'Shield',
  dashboard: 'LayoutDashboard',
  timeline:  'Activity',
  network:   'Network',
  ioc:       'Crosshair',
  case:      'FolderOpen',
  host:      'Monitor',
  intel:     'Globe',
  rules:     'SlidersHorizontal',
  reports:   'FileText',
  settings:  'Settings',
  search:    'Search',
  bell:      'Bell',
  filter:    'Filter',
  flag:      'Flag',
  link:      'Link',
  upload:    'Upload',
  bolt:      'Zap',
  globe:     'Globe',
  user:      'User',
};

export const BY_NAME = {
  Shield,
  LayoutDashboard,
  Activity,
  Network,
  Crosshair,
  FolderOpen,
  Monitor,
  Globe,
  SlidersHorizontal,
  FileText,
  Settings,
  Search,
  Bell,
  Filter,
  Flag,
  Link,
  Upload,
  Zap,
  User,
  ChevronRight,
  Info,
  ScrollText,
  Circle,
};

export default function Icon({ name, size = 14, strokeWidth = 1.6, ...props }) {
  const Cmp = BY_NAME[ICONS[name] || name] || Circle;
  return <Cmp size={size} strokeWidth={strokeWidth} {...props} />;
}
