// Static artifact metadata shared by native parsing and CSV mapping derivation.
// Kept out of routes/collection.js so it can be consumed without importing the router.
const path = require('path');
const fs = require('fs');

const ZIMMERMAN_DIR = process.env.ZIMMERMAN_TOOLS_DIR || '/app/zimmerman-tools';

const ARTIFACT_PATTERNS = {
  evtx: {
    patterns: ['**/*.evtx', '**/winevt/Logs/*.evtx'],
    tool: 'EvtxECmd.dll',
    toolKey: 'evtx',
    name: 'Event Logs',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'EvtxECmd.dll'), '-d', input, '--csv', output, '--csvf', 'evtx_results.csv'],
    toolEnv: { DOTNET_SYSTEM_THREADING_THREADPOOL_MINTHREADS: '4', DOTNET_SYSTEM_THREADING_THREADPOOL_MINCOMPLETIONPORTTHREADS: '4' },
    timestampColumns: ['TimeCreated', 'SystemTime'],
    descriptionColumns: ['MapDescription', 'PayloadData1'],
    sourceColumn: 'Channel',
  },
  prefetch: {
    patterns: ['**/Prefetch/*.pf', '**/*.pf'],
    tool: 'PECmd.dll',
    toolKey: 'prefetch',
    name: 'PECmd',
    argsBuilder: (input, output) => {
      const dir = fs.statSync(input).isDirectory() ? input : path.dirname(input);
      return ['dotnet', path.join(ZIMMERMAN_DIR, 'PECmd.dll'), '-d', dir, '--csv', output, '--csvf', 'prefetch_results.csv', '-q'];
    },
    timestampColumns: ['LastRun', 'SourceCreated', 'SourceModified'],
    descriptionColumns: ['ExecutableName'],
    sourceColumn: 'SourceFilename',
  },
  mft: {
    patterns: ['**/$MFT', '**/MFT/$MFT', '**/$MFT*'],
    tool: 'MFTECmd.dll',
    toolKey: 'mft',
    name: '$MFT',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'MFTECmd.dll'), '-f', input, '--csv', output, '--csvf', 'mft_results.csv'],
    toolEnv: { DOTNET_SYSTEM_THREADING_THREADPOOL_MINTHREADS: '2', DOTNET_SYSTEM_THREADING_THREADPOOL_MINCOMPLETIONPORTTHREADS: '2' },
    timestampColumns: ['Created0x10', 'Created0x30', 'LastModified0x10', 'LastAccess0x10'],
    descriptionColumns: ['FileName'],
    sourceColumn: 'ParentPath',
  },
  usn: {
    patterns: ['**/$Extend/$UsnJrnl*', '**/$UsnJrnl*$J', '**/$UsnJrnl_$J', '**/$J'],
    tool: 'MFTECmd.dll',
    toolKey: 'usn',
    name: '$J (USN Journal)',
    // -f $J ; parent-path resolution would need -m $MFT (added later if a sibling $MFT is collected).
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'MFTECmd.dll'), '-f', input, '--csv', output, '--csvf', 'usn_results.csv'],
    timestampColumns: ['UpdateTimestamp'],
    descriptionColumns: ['Name', 'UpdateReasons'],
    sourceColumn: 'ParentPath',
  },
  indx: {
    patterns: ['**/$I30', '**/*_$I30', '**/$I30*'],
    tool: 'MFTECmd.dll',
    toolKey: 'indx',
    name: '$I30 (INDX)',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'MFTECmd.dll'), '-f', input, '--csv', output, '--csvf', 'indx_results.csv'],
    timestampColumns: ['LastModified0x10', 'Created0x10', 'LastAccess0x10'],
    descriptionColumns: ['FileName'],
    sourceColumn: 'ParentPath',
  },
  lnk: {
    patterns: ['**/Recent/**/*.lnk', '**/*.lnk'],
    tool: 'LECmd.dll',
    toolKey: 'lnk',
    name: 'LNK Shortcuts',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'LECmd.dll'), '-d', input, '--csv', output, '--csvf', 'lnk_results.csv'],
    timestampColumns: ['SourceCreated', 'SourceModified', 'TargetCreated', 'TargetModified'],
    descriptionColumns: ['LocalPath', 'SourceFile'],
    sourceColumn: 'SourceFile',
  },
  registry: {
    patterns: ['**/config/SAM', '**/config/SECURITY', '**/config/SOFTWARE', '**/config/SYSTEM', '**/NTUSER.DAT', '**/UsrClass.dat'],
    tool: 'RECmd.dll',
    toolKey: 'registry',
    name: 'Registry Hives',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'RECmd.dll'), '-f', input, '--csv', output, '--csvf', 'registry_results.csv', '--bn', path.join(ZIMMERMAN_DIR, 'BatchExamples', 'RECmd_Batch_MC.reb')],
    timestampColumns: ['LastWriteTimestamp'],
    descriptionColumns: ['Description', 'ValueName'],
    sourceColumn: 'HivePath',
  },
  amcache: {
    patterns: ['**/Amcache.hve', '**/appcompat/Programs/Amcache.hve'],
    tool: 'AmcacheParser.dll',
    toolKey: 'amcache',
    name: 'Amcache',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'AmcacheParser.dll'), '-f', input, '--csv', output, '--csvf', 'amcache_results.csv'],
    timestampColumns: ['FileKeyLastWriteTimestamp', 'LinkDate'],
    descriptionColumns: ['FileDescription', 'FullPath', 'ProgramName', 'KeyName'],
    sourceColumn: 'ProgramName',
  },
  appcompat: {
    patterns: ['**/config/SYSTEM', '**/SYSTEM'],
    tool: 'AppCompatCacheParser.dll',
    toolKey: 'appcompat',
    name: 'ShimCache (AppCompat)',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'AppCompatCacheParser.dll'), '-f', input, '--csv', output, '--csvf', 'shimcache_results.csv'],
    timestampColumns: ['LastModifiedTimeUTC', 'CacheEntryPosition'],
    descriptionColumns: ['Path'],
    sourceColumn: 'SourceFile',
  },
  shellbags: {
    patterns: ['**/UsrClass.dat', '**/NTUSER.DAT'],
    tool: 'SBECmd.dll',
    toolKey: 'shellbags',
    name: 'Shellbags',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'SBECmd.dll'), '-d', input, '--csv', output],
    timestampColumns: ['CreatedOn', 'ModifiedOn', 'AccessedOn', 'LastWriteTime'],
    descriptionColumns: ['AbsolutePath'],
    sourceColumn: 'AbsolutePath',
  },
  jumplist: {
    patterns: ['**/*.automaticDestinations-ms', '**/*.customDestinations-ms'],
    tool: 'JLECmd.dll',
    toolKey: 'jumplist',
    name: 'Jump Lists',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'JLECmd.dll'), '-d', input, '--csv', output, '--csvf', 'jumplist_results.csv'],
    timestampColumns: ['SourceCreated', 'SourceModified', 'TargetCreated', 'TargetModified'],
    descriptionColumns: ['AppIdDescription', 'LocalPath'],
    sourceColumn: 'SourceFile',
  },
  srum: {
    patterns: ['**/SRUDB.dat'],
    tool: 'SrumECmd.dll',
    toolKey: 'srum',
    name: 'SrumECmd',

    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_srum.py', '-f', input, '--csv', output, '--csvf', 'srum_results.csv'],
    timestampColumns: ['Timestamp', 'ConnectStartTime'],
    descriptionColumns: ['ExeInfo'],
    sourceColumn: 'AppId',
  },
  wxtcmd: {
    patterns: ['**/ActivitiesCache.db'],
    tool: 'WxTCmd.dll',
    toolKey: 'wxtcmd',
    name: 'Windows Timeline',

    argsBuilder: (input, output) => {
      const dir = fs.statSync(input).isDirectory() ? input : path.dirname(input);
      return ['python3', '/app/parsers/parse_wxtcmd.py', '-d', dir, '--csv', output, '--csvf', 'wxtcmd_results.csv'];
    },
    timestampColumns: ['StartTime', 'EndTime', 'LastModifiedTime'],
    descriptionColumns: ['DisplayText', 'Description', 'AppId'],
    sourceColumn: 'AppId',
  },
  userassist: {
    patterns: ['**/NTUSER.DAT', '**/NTUSER.dat'],
    tool: 'parse_userassist.py',
    toolKey: 'userassist',
    name: 'UserAssist',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_userassist.py', '-f', input, '--csv', output, '--csvf', 'userassist_results.csv'],
    timestampColumns: ['LastExecuted'],
    descriptionColumns: ['ProgramName'],
    sourceColumn: 'ProgramName',
  },
  netprofile: {
    patterns: ['**/SOFTWARE', '**/Software', '**/config/SOFTWARE'],
    tool: 'parse_networklist.py',
    toolKey: 'netprofile',
    name: 'Profils réseau',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_networklist.py', '-f', input, '--csv', output, '--csvf', 'networklist_results.csv'],
    timestampColumns: ['DateLastConnected', 'DateCreated'],
    descriptionColumns: ['ProfileName', 'DnsSuffix', 'GatewayMac'],
    sourceColumn: 'ProfileName',
  },
  usb: {
    patterns: ['**/setupapi.dev.log', '**/INF/setupapi.dev.log', '**/inf/setupapi.dev.log'],
    tool: 'parse_usb.py',
    toolKey: 'usb',
    name: 'Historique USB',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_usb.py', '-f', input, '--csv', output, '--csvf', 'usb_results.csv'],
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['DeviceDescription', 'DeviceInstanceId'],
    sourceColumn: 'DeviceInstanceId',
  },
  schtasks: {
    patterns: ['**/System32/Tasks/**', '**/Windows/Tasks/**', '**/Tasks/**'],
    tool: 'parse_schtasks.py',
    toolKey: 'schtasks',
    name: 'Tâches planifiées',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_schtasks.py', '-d', input, '--csv', output, '--csvf', 'schtasks_results.csv'],
    timestampColumns: ['Date'],
    descriptionColumns: ['TaskName', 'Command'],
    sourceColumn: 'TaskName',
  },
  pwsh: {
    patterns: ['**/ConsoleHost_history.txt'],
    tool: 'parse_pwsh_history.py',
    toolKey: 'pwsh',
    name: 'Historique PowerShell',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_pwsh_history.py', '-d', input, '--csv', output, '--csvf', 'pwsh_history_results.csv'],
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['Command'],
    sourceColumn: 'UserName',
  },
  dns: {
    patterns: ['**/drivers/etc/hosts', '**/etc/hosts', '**/*displaydns*.txt', '**/*DnsCache*.txt'],
    tool: 'parse_dns.py',
    toolKey: 'dns',
    name: 'DNS / hosts',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_dns.py', '-d', input, '--csv', output, '--csvf', 'dns_results.csv'],
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['Entry'],
    sourceColumn: 'Type',
  },
  webcache: {
    patterns: ['**/WebCacheV01.dat', '**/WebCacheV*.dat', '**/WebCache/WebCacheV*.dat'],
    tool: 'parse_webcache.py',
    toolKey: 'webcache',
    name: 'WebCache (IE/Edge)',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_webcache.py', '-f', input, '--csv', output, '--csvf', 'webcache_results.csv'],
    timestampColumns: ['AccessedTime', 'ModifiedTime'],
    descriptionColumns: ['Url'],
    sourceColumn: 'ContainerType',
  },
  pcap: {
    patterns: ['**/*.pcap', '**/*.pcapng', '**/*.cap'],
    tool: 'parse_pcap.py',
    toolKey: 'pcap',
    name: 'Capture réseau (PCAP)',
    // Custom dispatch in the parse route inserts flows into network_connections (not the timeline).
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_pcap.py', '-d', input, '--csv', output, '--csvf', 'pcap_results.csv'],
    timestampColumns: ['first_seen'],
    descriptionColumns: [],
    sourceColumn: '',
  },
  wmi: {
    patterns: ['**/wbem/Repository/**/OBJECTS.DATA', '**/OBJECTS.DATA'],
    tool: 'parse_wmi.py',
    toolKey: 'wmi',
    name: 'Persistance WMI',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_wmi.py', '-d', path.dirname(input), '--csv', output, '--csvf', 'wmi_results.csv'],
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['Type', 'Name', 'Detail'],
    sourceColumn: 'Type',
  },
  rdpcache: {
    patterns: ['**/bcache*.bmc', '**/Cache/Cache*.bin', '**/Terminal Server Client/Cache/**', '**/Cache????.bin'],
    tool: 'bmc-tools.py',
    toolKey: 'rdpcache',
    name: 'RDP Bitmap Cache',
    // Custom dispatch reconstructs PNG tiles into a served dir (not the timeline).
    argsBuilder: (input, output) => ['python3', '/app/tools/bmc-tools.py', '-s', path.dirname(input), '-d', output, '-b'],
    timestampColumns: [],
    descriptionColumns: [],
    sourceColumn: '',
  },
  recycle: {
    patterns: ['**/$Recycle.Bin/**/$I*', '**/$I*'],
    tool: 'RBCmd.dll',
    toolKey: 'recycle',
    name: 'Recycle Bin ($I)',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'RBCmd.dll'), '-d', input, '--csv', output],
    timestampColumns: ['DeletedOn'],
    descriptionColumns: ['FileName'],
    sourceColumn: 'SourceName',
  },
  bits: {
    patterns: ['**/qmgr*.dat', '**/BITS/**'],
    tool: 'BitsParser.dll',
    toolKey: 'bits',
    name: 'BITS Jobs',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'BitsParser.dll'), '-f', input, '--csv', output],
    timestampColumns: ['CreationTime', 'ModifiedTime', 'CompletedTime'],
    descriptionColumns: ['JobName'],
    sourceColumn: 'TargetDirectory',
  },
  sum: {
    patterns: ['**/Current.mdb', '**/SystemIdentity.mdb'],
    tool: 'SumECmd.dll',
    toolKey: 'sum',
    name: 'User Access Logging',
    argsBuilder: (input, output) => ['dotnet', path.join(ZIMMERMAN_DIR, 'SumECmd.dll'), '-d', input, '--csv', output],
    timestampColumns: ['InsertDate', 'LastAccess'],
    descriptionColumns: ['UserName'],
    sourceColumn: 'UserName',
  },
  sqle: {

    patterns: ['**/History', '**/places.sqlite', '**/formhistory.sqlite',
               '**/downloads.sqlite', '**/cookies.sqlite'],
    tool: 'SQLECmd.dll',
    toolKey: 'sqle',
    name: 'Browser History',
    argsBuilder: (input, output) => ['python3', '/app/parsers/parse_sqle.py', '-d', input, '--csv', output, '--csvf', 'sqle_results.csv'],
    timestampColumns: ['LastVisitDate', 'VisitDate', 'StartTime'],
    descriptionColumns: ['Title', 'URL'],
    sourceColumn: 'SourceFile',
  },
  auditd: {
    patterns: ['**/audit/audit.log', '**/audit/audit.log.*', '**/log/audit/**'],
    tool: 'parse_auditd.py',
    toolKey: 'auditd',
    name: 'Linux Auditd',
    argsBuilder: (input, output) => {
      const dir = require('fs').statSync(input).isDirectory() ? input : require('path').dirname(input);
      return ['python3', '/app/parsers/parse_auditd.py', '-d', dir, '--csv', output, '--csvf', 'auditd_results.csv'];
    },
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['AuditType', 'Exe', 'Args'],
    sourceColumn: 'HostName',
  },
  syslog: {
    patterns: ['**/log/syslog', '**/log/messages', '**/log/auth.log', '**/log/secure',
               '**/log/syslog.*', '**/log/messages.*'],
    tool: 'parse_syslog.py',
    toolKey: 'syslog',
    name: 'Linux Syslog',
    argsBuilder: (input, output) => {
      const dir = require('fs').statSync(input).isDirectory() ? input : require('path').dirname(input);
      return ['python3', '/app/parsers/parse_syslog.py', '-d', dir, '--csv', output, '--csvf', 'syslog_results.csv'];
    },
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['Program', 'Message'],
    sourceColumn: 'Program',
  },
  bash_history: {
    patterns: ['**/.bash_history', '**/.zsh_history', '**/.zhistory', '**/bash_history'],
    tool: 'parse_bash_history.py',
    toolKey: 'bash_history',
    name: 'Bash/Zsh History',
    argsBuilder: (input, output) => {
      const dir = require('fs').statSync(input).isDirectory() ? input : require('path').dirname(input);
      return ['python3', '/app/parsers/parse_bash_history.py', '-d', dir, '--csv', output, '--csvf', 'bash_history_results.csv'];
    },
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['Command'],
    sourceColumn: 'UserName',
  },
  unified_log: {
    patterns: ['**/*.logarchive/**', '**/unified_log*.json', '**/unified_log*.txt',
               '**/system.log', '**/system.log.*'],
    tool: 'parse_unified_log.py',
    toolKey: 'unified_log',
    name: 'macOS Unified Log',
    argsBuilder: (input, output) => {
      const dir = require('fs').statSync(input).isDirectory() ? input : require('path').dirname(input);
      return ['python3', '/app/parsers/parse_unified_log.py', '-d', dir, '--csv', output, '--csvf', 'unified_log_results.csv'];
    },
    timestampColumns: ['Timestamp'],
    descriptionColumns: ['ProcessName', 'Message'],
    sourceColumn: 'ProcessName',
  },
};

const ECS_COLUMNS = {
  evtx:      { host: ['Computer', 'ComputerName'], user: ['SubjectUserName', 'TargetUserName', 'RemoteUserName', 'SourceUserName', 'UserName'], process: ['ProcessName', 'NewProcessName', 'Image'] },
  prefetch:  { host: ['Computer', 'ComputerName'], user: ['OSUser', 'UserName'], process: ['ExecutableName'] },
  mft:       { host: ['ComputerName'], user: ['UserName', 'OwnerSid'], process: [] },
  lnk:       { host: ['MachineID', 'NetBiosMachineName', 'ComputerName'], user: ['UserName', 'LocalUser'], process: [] },
  jumplist:  { host: ['MachineID', 'NetBiosMachineName'], user: ['UserName'], process: ['AppIdDescription'] },
  shellbags: { host: ['ComputerName'], user: ['UserName', 'HiveUser'], process: [] },
  amcache:   { host: ['ComputerName'], user: ['UserName', 'OSUser'], process: ['ProgramName'] },
  appcompat: { host: ['ComputerName', 'SourceFile'], user: ['UserName'], process: [] },
  registry:  { host: ['ComputerName', 'HiveName'], user: ['UserName', 'HiveUser'], process: [] },
  srum:      { host: ['ComputerName'], user: ['UserSid', 'UserName'], process: ['ExeInfo'] },
  sqle:      { host: ['ComputerName', 'HostName'], user: ['Profile', 'UserName'], process: [] },
  wxtcmd:    { host: ['ComputerName', 'DeviceId'], user: ['Sid', 'UserName'], process: [] },
  recycle:   { host: ['ComputerName'], user: ['UserName', 'DeletedBy'], process: [] },
  bits:      { host: ['ComputerName'], user: ['UserName', 'Owner'], process: ['JobName'] },
  sum:       { host: ['ClientName', 'ComputerName'], user: ['UserName', 'AuthenticatedUserName'], process: [] },
  usn:       { host: ['ComputerName'], user: [], process: [] },
  indx:      { host: ['ComputerName'], user: [], process: [] },
  userassist:{ host: ['ComputerName'], user: ['UserName'], process: ['ProgramName'] },
  netprofile:{ host: ['ComputerName'], user: [], process: [] },
  usb:       { host: ['ComputerName'], user: [], process: [] },
  schtasks:  { host: ['ComputerName'], user: ['RunAs', 'Author'], process: ['Command'] },
  pwsh:      { host: ['ComputerName'], user: ['UserName'], process: [] },
  dns:       { host: ['ComputerName'], user: [], process: [] },
  webcache:  { host: ['ComputerName'], user: [], process: [] },
  wmi:       { host: ['ComputerName'], user: [], process: [] },
  hayabusa:  { host: ['Computer', 'ComputerName'], user: ['SubjectUserName', 'TargetUserName', 'UserName'], process: ['ProcessName', 'Image'] },
  auditd:    { host: ['HostName'], user: ['UserName'], process: ['Exe'] },
  syslog:    { host: ['HostName'], user: [], process: ['Program'] },
  bash_history: { host: [], user: ['UserName'], process: [] },
  unified_log: { host: ['HostName'], user: [], process: ['ProcessName'] },
};

module.exports = { ZIMMERMAN_DIR, ARTIFACT_PATTERNS, ECS_COLUMNS };
